-- Membership master tables
-- PostgreSQL compatible

CREATE TABLE IF NOT EXISTS membership_types (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by integer NULL,
  updated_at timestamp NULL,
  deleted_by integer NULL,
  deleted_at timestamp NULL
);

CREATE INDEX IF NOT EXISTS idx_membership_types_status ON membership_types (status);
CREATE INDEX IF NOT EXISTS idx_membership_types_deleted_at ON membership_types (deleted_at);

CREATE TABLE IF NOT EXISTS membership_plans (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(150) NULL,
  fees real NULL,
  fee_type varchar(50) NOT NULL DEFAULT '/ year',
  status integer DEFAULT 1,
  created_by integer NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by integer NULL,
  updated_at timestamp NULL,
  deleted_by integer NULL,
  deleted_at timestamp NULL
);

CREATE INDEX IF NOT EXISTS idx_membership_plans_status ON membership_plans (status);
CREATE INDEX IF NOT EXISTS idx_membership_plans_deleted_at ON membership_plans (deleted_at);

CREATE TABLE IF NOT EXISTS membership_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membership_type_id integer NULL,
  name varchar(100) NULL,
  short_name varchar(50) NULL,
  fee double precision NULL,
  fee_type varchar(50) DEFAULT '/ year',
  founding_member smallint DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  created_by integer NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by integer NULL,
  updated_at timestamp NULL,
  deleted_by integer NULL,
  deleted_at timestamp NULL,
  CONSTRAINT fk_membership_categories_membership_type
    FOREIGN KEY (membership_type_id) REFERENCES membership_types (id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_membership_categories_membership_type_id ON membership_categories (membership_type_id);
CREATE INDEX IF NOT EXISTS idx_membership_categories_status ON membership_categories (status);
CREATE INDEX IF NOT EXISTS idx_membership_categories_deleted_at ON membership_categories (deleted_at);
